name: "MGO2PC/hetzner-cloud"
description: "Destroy all servers from a GitHub Action"
author: "cipherxof"
inputs:
  hcloud-token:
    description: "Your Hetzner Cloud API token."
    required: true

runs:
  using: 'node12'
  main: 'dist/destroy/index.js'

branding:
  icon: server
  color: "yellow"
